### ISSUE TITLE
[MEETUP] SSH

### ISSUE THREAD

**Issue by mitilan** [CyberSecurityClubMoscow/meetups#11]
SSH - это не просто замена telnet. Обсуждаем стэк протоколов.

**Comment by mitilan** [comment]
Для начала немного истории https://twitter.com/openbsdnow/status/1322514787776008194?s=21

**Comment by mitilan** [comment]
**RFCs**
More Modular Exponentiation (MODP) Diffie-Hellman (DH)
Key Exchange (KEX) Groups for Secure Shell (SSH)
https://tools.ietf.org/html/rfc8268

Extension Negotiation in the Secure Shell (SSH) Protocol
https://tools.ietf.org/html/rfc8308

SHA-2 Data Integrity Verification for the Secure Shell (SSH) Transport Layer Protocol
https://tools.ietf.org/html/rfc6668

Use of RSA Keys with SHA-256 and SHA-512 in the Secure Shell (SSH) Protocol
https://tools.ietf.org/html/rfc8332

Ed25519 and Ed448 Public Key Algorithms for the Secure Shell (SSH) Protocol
https://tools.ietf.org/html/rfc8709

Deprecating RC4 in Secure Shell (SSH)
https://tools.ietf.org/html/rfc8758

Using DNS to Securely Publish Secure Shell (SSH) Key Fingerprints
https://tools.ietf.org/html/rfc4255

Generic Message Exchange Authentication for the Secure Shell Protocol (SSH)
https://tools.ietf.org/html/rfc4256

**Comment by mitilan** [comment]
SSH protocol from Computerphile
https://www.youtube.com/watch?v=ORcvSkgdA58

**Comment by mitilan** [comment]
**SSH Academy**, a perfect entry point into SSH world; from SSH basics and tools to SSH Compliance in Enterprises
https://www.ssh.com/ssh/

**Comment by mitilan** [comment]
Famous SSH Mastery:
https://www.amazon.com/SSH-Mastery-OpenSSH-PuTTY-Tunnels/dp/1642350028

**Comment by mitilan** [comment]
Decrypting SSH session
https://blog.fox-it.com/2020/11/11/decrypting-openssh-sessions-for-fun-and-profit/

**Comment by mitilan** [comment]
Short and clear how-to on ssh multiplexing
https://blog.scottlowe.org/2015/12/11/using-ssh-multiplexing/

**Comment by mitilan** [comment]
SSH certificates
https://medium.com/better-programming/how-to-use-ssh-certificates-for-scalable-secure-and-more-transparent-server-access-720a87af6617

**Comment by Andrysky** [comment]
можете пожалуйста запись видео выложить или хотя бы в личку кинуть, а то не сумел присутствовать а очень интересует тема и нужно в неё погрузиться, и очень хочется хоть немного понимать поверхностно перред погружением.

**Comment by mitilan** [comment]
Записи нет. Выложил слайды, вдруг интересно будет https://www2.slideshare.net/IlyaMitrukov/ssh-protocol-description
Мб руки дойдут и выложу команды и элементы конфигов, которые рассмотрели на митапе, в репо на неделе.
