### ISSUE TITLE
[MEETUP] Network Intrusion Detection

### ISSUE THREAD

**Issue by mitilan** [CyberSecurityClubMoscow/meetups#12]
tbd

**Comment by DoctorGift** [comment]
Как разбирать шифрованный трафик, если, к примеру, ссл терминируется на уровне приложения? Как разбирать трафик между протоколами бинарного обмена, например на сокетах или тот же протобуф? Интеграция Snort и Suricata, практики использования, бэст практис? И последнее, но не по важности, когда Snort может быть не нужен или нет смысла в его использовании, и чем заменить?

**Comment by mitilan** [comment]
Просто Suricata https://suricata-ids.org/webinars/
Просто Snort https://www.snort.org
