### ISSUE TITLE
[MEETUP] SELinux

### ISSUE THREAD

**Issue by mitilan** [CyberSecurityClubMoscow/meetups#2]
SELinux architecture, demo.

**Comment by mitilan** [comment]
SELinux tutorial от Digital Ocean. Не зря поисковики ставят на первую строчку 

https://www.digitalocean.com/community/tutorials/an-introduction-to-selinux-on-centos-7-part-1-basic-concepts

**Comment by mitilan** [comment]
Свен Вермейлен «Администрирование системы защиты SELinux»

**Comment by mitilan** [comment]
Nice cheat sheet

https://opensource.com/article/18/7/sysadmin-guide-selinux

**Comment by mitilan** [comment]
Официальный док от NSA "Configuring the SELinux Policy"
https://www.nsa.gov/Portals/70/documents/resources/everyone/digital-media-center/publications/research-papers/configuring-selinux-policy-report.pdf

**Comment by mitilan** [comment]
Just Stop Disabling SELinux
http://stopdisablingselinux.com/

**Comment by mitilan** [comment]
SELinux Wiki from Gentoo - 
https://wiki.gentoo.org/wiki/SELinux

**Comment by dok2d** [comment]
В новом релизе ядра Linux ускорили работу SELinux

https://lore.kernel.org/lkml/CAHC9VhTX8gkUui6AiTJMJgcohXa=TOqdO==rEDk=Mquz9sCNKA@mail.gmail.com/
https://github.com/SELinuxProject/selinux-kernel/releases/tag/v5.8

https://www.phoronix.com/scan.php?page=news_item&px=Linux-5.8-SELinux-Optimizations
