### ISSUE TITLE
[MEETUP] Ханипоты

### ISSUE THREAD

**Issue by dok2d** [CyberSecurityClubMoscow/meetups#4]
Реализация всего, что можно назвать ханипотом

**Comment by dok2d** [comment]
И демо со сборкой ханипота по собранным предложениям, как вторая часть митапа

**Comment by mitilan** [comment]
> Реализация всего, что можно назвать ханипотом

Давно висит задача. Надо на кого-нибудь заасайнить )

**Comment by malinkinsa** [comment]
Ну как минимум можно посмотреть на cowrie и например забор его данных в тот же splunk/elk или готовый комбайн например T-Pot.

**Comment by dok2d** [comment]
https://habr.com/ru/company/alexhost/blog/528796/

**Comment by mitilan** [comment]
https://opencanary.readthedocs.io/

**Comment by dok2d** [comment]
https://xakep.ru/2020/07/28/deception/

**Comment by dok2d** [comment]
https://github.com/paralax/awesome-honeypots

**Comment by dok2d** [comment]
https://www.opennet.ru/opennews/art.shtml?num=53663
https://xakep.ru/2021/02/26/honeypots-catched/
