### ISSUE TITLE
[MEETUP] Превращение локальной файлопомойки в удаленный космолет. Безопасность, контейнеризация и прочее.

### ISSUE THREAD

**Issue by sanek8686** [CyberSecurityClubMoscow/meetups#8]
План митапа с точки зрения ИБ. 

1.	Заставка
2.	Бюджет
3.	Концепция обеспечения ИБ
4.	Структурная схема сети WAN/DMZ/LAN, точка доступа
5.	Пограничный МЭ. Основные задачи МЭ и функции
6.	Программный МЭ на сервере, защита извне и изнутри
7.	IDS/IPS для сервера
8.	Проброс портов (пара слов про удаленное администрирование), Honey Pot для взломщика
9.	Proxy для LAN
10.	Мониторинг событий сервера
11.	BackUp
12.	Функционал сервера (облако, сетевые ресурсы, торрент и прочее) и их защита
13.	Docker контейнеризация для обеспечения ИБ
14.   Домашняя песочница (dok2d)

**Comment by sanek8686** [comment]
Прошу подключиться всех заинтересованных. Хотелось бы чтобы митап получился живым и после него информационная безопасность не потекла из ушей )

**Comment by dok2d** [comment]
Готов приджойниться
@Dok2d в телеге

**Comment by dok2d** [comment]
https://www.clamav.net/about

**Comment by sanek8686** [comment]
Перед митапом неплохо бы было проверить работоспособность защиты - дать экспертную оценку по слабым местам предлогаемого концепта. 
Если есть опыт и желание попентестить, просьба отовзваться.

**Comment by sanek8686** [comment]
Бесплатные антивирусы и межсетевые экраны (UTM, NGFW) от Sophos
https://habr.com/ru/company/fgts/blog/448594/

**Comment by mitilan** [comment]
Заметки с чата митапа:
тулы /системы: 
lynis, rkhunter, fail2ban, iffier

ссылки: 
https://www.sophos.com/en-us/products/free-tools/sophos-utm-home-edition.aspx
https://ipfs.io
https://www.endian.com/de/community/comparison
https://www.youtube.com/watch?v=hDXVaIuuu-w
