### ISSUE TITLE
[MEETUP] Host Intrusion Detection

### ISSUE THREAD

**Issue by mitilan** [CyberSecurityClubMoscow/meetups#9]
Malware, вирусы, бэкдоры. Как обнаружить зловред и избавиться от него.

**Comment by mitilan** [comment]
Famous volatility 
https://github.com/volatilityfoundation/volatility

**Comment by mitilan** [comment]
Насколько антивирусы реально защищают от угроз - статистика / мнения экспертов.

**Comment by mitilan** [comment]
Анализ логов / обнаружение подозрительной активности. Инструменты

**Comment by mitilan** [comment]
Шифровальщики. Как определить кто поработал. Когда есть шансы расшифровать. Инструменты от вендоров.

**Comment by mitilan** [comment]
превентивные методы минимизации последствий (ограниченные учетки, права доступа, selinux, pledge, контейнеры ...).

**Comment by mitilan** [comment]
сканирование на RAT и прочие тулы двойного назначения

**Comment by mitilan** [comment]
MaxPatrol from Positive Technologies для инструментального анализа

**Comment by mitilan** [comment]
Государственные порталы про безопасность
https://safe-surf.ru/
https://www.dhs.gov

**Comment by dok2d** [comment]
SAST и DAST
https://habr.com/ru/company/pt/blog/305000/

**Comment by dok2d** [comment]
https://www.ossec.net

**Comment by mitilan** [comment]
https://www.tecmint.com/scan-linux-for-malware-and-rootkits/
